// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using DealUp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealUp.Database.Migrations
{
    [DbContext(typeof(PostgresqlContext))]
    [Migration("20250405121819_AddInitialMigration")]
    partial class AddInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealUp.Domain.Abstractions.EntityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DealUp.Domain.Abstractions.AuditableEntityBase", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.EntityBase");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Label", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.EntityBase");

                    b.Property<Guid?>("AdvertisementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("Name");

                    b.HasIndex("ProductId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Tag", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.EntityBase");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("Value");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Advertisement", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "DealUp.Domain.Advertisement.Advertisement.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Point>("Coordinates")
                                .IsRequired()
                                .HasColumnType("geography (point,4326)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Statistics", "DealUp.Domain.Advertisement.Advertisement.Statistics#AttendanceStatistics", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("ChatCount")
                                .HasColumnType("integer");

                            b1.Property<int>("FavoriteCount")
                                .HasColumnType("integer");

                            b1.Property<int>("ViewCount")
                                .HasColumnType("integer");
                        });

                    b.HasIndex("SellerId");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Product", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AdvertisementId")
                        .IsUnique();

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DealUp.Domain.Media.MediaEntity", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("MediaEntity");
                });

            modelBuilder.Entity("DealUp.Domain.Seller.SellerProfile", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SellerProfile");
                });

            modelBuilder.Entity("DealUp.Domain.User.User", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("DealUp.Domain.User.UserPendingConfirmation", b =>
                {
                    b.HasBaseType("DealUp.Domain.Abstractions.AuditableEntityBase");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("UserPendingConfirmation");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Label", b =>
                {
                    b.HasOne("DealUp.Domain.Advertisement.Advertisement", "Advertisement")
                        .WithMany("Labels")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DealUp.Domain.Advertisement.Product", "Product")
                        .WithMany("Labels")
                        .HasForeignKey("ProductId");

                    b.Navigation("Advertisement");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Tag", b =>
                {
                    b.HasOne("DealUp.Domain.Advertisement.Advertisement", "Advertisement")
                        .WithMany("Tags")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Advertisement", b =>
                {
                    b.HasOne("DealUp.Domain.Seller.SellerProfile", "Seller")
                        .WithMany("Advertisements")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Product", b =>
                {
                    b.HasOne("DealUp.Domain.Advertisement.Advertisement", null)
                        .WithOne("Product")
                        .HasForeignKey("DealUp.Domain.Advertisement.Product", "AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealUp.Domain.Media.MediaEntity", b =>
                {
                    b.HasOne("DealUp.Domain.Advertisement.Advertisement", null)
                        .WithMany("Media")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealUp.Domain.Seller.SellerProfile", b =>
                {
                    b.HasOne("DealUp.Domain.User.User", "User")
                        .WithOne()
                        .HasForeignKey("DealUp.Domain.Seller.SellerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealUp.Domain.User.UserPendingConfirmation", b =>
                {
                    b.HasOne("DealUp.Domain.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Advertisement", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Media");

                    b.Navigation("Product")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DealUp.Domain.Advertisement.Product", b =>
                {
                    b.Navigation("Labels");
                });

            modelBuilder.Entity("DealUp.Domain.Seller.SellerProfile", b =>
                {
                    b.Navigation("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
