name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: docker-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/DealUp.Application.Api/Dockerfile
          push: true
          tags: zvesdochyot/dealup-api:latest
          platforms: linux/amd64,linux/arm64
